# Generated by Django 2.2.5 on 2021-06-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='alias',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
